### ISSUE TITLE
How do I reset the database state?

### ISSUE THREAD

**Issue by theultimatehorse** [miguelgrinberg/Flask-Migrate#184]
Hey, I'm having trouble finding out how I can apply all migrations to a newly created database, or rather, the same database, after deleting all its tables.

I tried `flask db upgrade` but an error is thrown:

` sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'testdb.team' doesn't exist") [SQL: 'SELECT team.id AS team_id, team.date_created AS team_date_created, team.date_modified AS team_date_modified, team.name AS team_name, team.country AS team_country \nFROM team'] (Background on this error at: http://sqlalche.me/e/f405)`

Full call stack: [pastebin](https://pastebin.com/yrv8gJxK)

What should I do in order to apply all migrations back to a _new_ database?

Thanks!

**Comment by miguelgrinberg** [comment]
Did you delete all the tables, or just all the tables that you know about? There is an extra table that is used to track migrations, that needs to go as well if you want to start from scratch.

**Comment by theultimatehorse** [comment]
I did, you're referring to the Alembic table, right?

**Comment by miguelgrinberg** [comment]
Yes. If you deleted the `alembic_version` table as well as all your own tables, then running `flask db upgrade` should have created everything anew. If you are getting an error still, then my guess is that the problem is in one of your migration scripts, which may be incorrectly written. Look at the stacktrace of your error to track down which migration script is failing and debug from there.

**Comment by theultimatehorse** [comment]
Oh, I was calling an initialization method on my models class which apparently is being called when you run upgrade. That fixed it!

Thanks for your help!
