### ISSUE TITLE
changing log level in configuration callback

### ISSUE THREAD

**Issue by bugsduggan** [miguelgrinberg/Flask-Migrate#208]
Following the docs, I am trying to alter the log level in the configuration to turn off logging:

```python
@migrate.configure
def configure_alembic(config):
    config.set_section('logger_alembic', 'level', 'WARN')
    return config
```

I've confirmed that making this same change in `alembic.ini` turns off logging successfully - but I don't want to change the "default" level as pulled from that file.

Unfortunately, this does not seem to work. I have tried outputting the level from the logger (in various locations) and every time it reports it as `WARN` but still outputs logs at `INFO` level.

Any help or suggestions would be gratefully received.

**Comment by miguelgrinberg** [comment]
The problem is that the default `env.py` file that is placed in your migrations directory reads the logging configuration from the alembic.ini file, and this happens after the config callbacks are called. See https://github.com/miguelgrinberg/Flask-Migrate/blob/master/flask_migrate/templates/flask/env.py#L13. You can comment out this line and then the logging changes will work.

The idea of the config callback was not to override the items that are in alembic.ini, which are mostly related to logging and are more easily changed in the config file directly. The idea was to insert new items.

**Comment by bugsduggan** [comment]
Thank you for your response - it's lead me to a slightly hacky but still effective solution to my usecase:
I'm setting `config.config_file_name` to `None` and then checking that in the `env.py` file, only setting up loggers if it has a value.

I really appreciate your help.
