### ISSUE TITLE
Flask-Migration all time create whole table

### ISSUE THREAD

**Issue by tojkamaster** [miguelgrinberg/Flask-Migrate#215]
Hi I have small table in sqlalchemy model.

1. After "flask db init" migrations directory has been created successfull - OK
2. After "falsk db migrate" migration has been created successfully
3. After "flask db upgrade" my table was created and it is ok.
4. In my sqlAlchemy model I've added one string column called "description"
5. after "flask db migrate" Flask-Migrate create migration file with full table definition - not only one new field. So when I'm executing "flask db upgrade" I have error: "Table 'users' already exists"

Looks like bug and I can't working with migrations.

**Comment by miguelgrinberg** [comment]
If it is a bug, it is one in Alembic, which is the migration engine you are using underneath Flask-Migrate. This package is just a Flask friendly interface to Alembic, it has nothing to do with the actual migrations.

That said, my guess is that there is something in your environment that is causing this. Do you have the output of all the commands you listed above? That would be useful to see.

**Comment by tincumagic** [comment]
I have encountered the same issue described by	tojkamaster.
The solution was for me to change the case of the table model to lower case from
    __tablename__ = 'APILOGS'
 to 
    __tablename__ = 'apilogs'
I also changed the case of the columns to lowecase everywhere, after that I worked very well. Same thing I am recommending for sequence names.

Additionaly:
Another change that I did was to remove the argument __table_args__ which contained only the schema variable.
Also to set Base to db model:
    Base = db.Model  # same default declarative base used by the engine
instead of:
   Base = declarative_base()

The init_db() looks like this:
def init_db():
    """Initialize SqlAlchemy for flask ext, we create the global Base, db
    :return None: """
    print("SqlAlchemy db engine creation")
    global db, Base, Session, migrate
    db = SQLAlchemy(app=app, session_options={"autoflush": False, "autocommit": False, "expire_on_commit": False})
    Session = sessionmaker(bind=db.engine)
    Base = db.Model  # same default declarative base used by the engine
    # Base = declarative_base() the Flask-Migrate needs db.Model not declarative_base()
    migrate = Migrate(app, db)
    print("init_db done")

The models are created like this:
class ApiLogs(Base):
    __tablename__ = 'apilogs'

    id = Column(Integer, Sequence('apilogid'), primary_key=True)
    start = Column(DateTime, nullable=False, default=datetime.datetime.now, doc="Request star time UTC+3", index=True)
