### ISSUE TITLE
flask_migrate.upgrade(directory=..) breaks logging

### ISSUE THREAD

**Issue by roman-telepathy-ai** [miguelgrinberg/Flask-Migrate#227]
On app start, we do migrations before the actual app gets running.
Procedure:
```
* create_app
* register extensions (DB, migrate, cache, ...)
* ping dependencies
* migrate
<<< HERE IS THE PROBLEM >>>
* start app
```
Note: do not worry why migration is done on every app start or about the concurrency during migration.

Problem:
before `flask_migrate.upgrade(directory=..) ` call all loggers of the app are working well, after the call, none of logger can log anything. I check already all attributes of logger and its handler and they are unchanged.

When disabling the migration call, then logs works; with migration - after the call no logging at all.

E.g. ` _logger.info('released DB lock')` at the bottom in the snippet is not logging anymore.

Snippet
```
            _logger.info('DB lock acquired')
            try:
                with _app.app_context():
                    flask_migrate.upgrade(directory=_migrate.directory)
            except Exception as e:
                _logger.error('DB upgrade failed %s :: %s' % (type(e), e))
                raise e
            finally:
                print('-release...')
                _lock.release()
                print('-releaseD!!!...')
                _logger.info('released DB lock')
```

Console
```
[2018-09-13 12:49:38,121] INFO: === perform DB upgrade
[2018-09-13 12:49:38,121] INFO: > migrations: /home/roman/repos/myrepo/server/pyserver/migrations
<logging.Logger object at 0x7f95bb734f98>
10
[<logging.StreamHandler object at 0x7f95bb748c88>, <logstash.handler_tcp.TCPLogstashHandler object at 0x7f95bb748320>]
[2018-09-13 12:49:38,121] INFO: DB lock acquired
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
-release...
-releaseD!!!...
<logging.Logger object at 0x7f95bb734f98>
10
[<logging.StreamHandler object at 0x7f95bb748c88>, <logstash.handler_tcp.TCPLogstashHandler object at 0x7f95bb748320>]
 * Tip: There are .env files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app "microservice_datacollection" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
```

Any help is welcome!

thx, r

**Comment by roman-telepathy-ai** [comment]
the only solution to fix that was to assign a new logger with new handlers after migration call

**Comment by miguelgrinberg** [comment]
This extension does not alter the logging configuration in any way, but I suspect alembic might. You may be able to workaround it if you invoke the migrate command as an external sub-process.

**Comment by roman-telepathy-ai** [comment]
thx for reply.
as I said I have a workaround, not nice but  works.

I will check alembic.

thx!

**Comment by jslay88** [comment]
It is alembic, but it can a fix can also be provided here as well.

I have successfully added my own implementation to flask_migrate that seems to work as expected. It all stems from the `init` and how the configuration is passed to `env.py`

Ref https://stackoverflow.com/questions/42427487/using-alembic-config-main-redirects-log-output

In the `env.py` files, I have added this @ ln # 17

```
if config.attributes.get('configure_logger', True):
    fileConfig(config.config_file_name)
```

And then to the `init` command and `Migrate.get_config ` method

```
def init(directory=None, multidb=False, attributes=None):
...
    if attributes is not None:
        for k, v in attributes.items():
            config.attributes[k] = v
```

And the `migrate`, `upgrade`, etc commands
```
def upgrade(... attributes=None):
    config = current_app.extensions['migrate'].migrate.get_config(directory,
                                                                  x_arg=x_arg,
                                                                  attributes=attributes)
```

Obviously this is not built up for dist or anything but Python3, but this is something that could be done to help provide the option for those that are using the methods directly within the app (such as apps that help provision the DB configuration and management from within the app)

**Comment by madkote** [comment]
@jslay88 thanks for your comment. we check it.

**Comment by jslay88** [comment]
Another issue I am running into, is that if there are any errors, the @catch_errors calls `sys.exit(1)` and prevents us from being able to do anything of handling of our own sorts. If anything, (even in CLI), this should not happen when you may expect the function to be imported as a module (such as documentation says we can). You should just call `raise` and let python re-raise the exception. If it is CLI, you make a CLI function, or make an arg that we can handle errors on our own. 

This is very close to where developers can properly do things entirely through flask_migrate and their flask application, and leave CLI there for when things hit the fan. Effectively, I am trying to have to app manage the upgrades and provide a front end for doing so to make managing the application in the wild much easier.

**Comment by miguelgrinberg** [comment]
@jslay88 why is it a problem to create your migration repository using one of the two provided templates and then make the modifications to alembic.ini and/or env.py that suit your needs? This is an infrequent operation that is done at the start of a project, these templated files are supposed to be a starting point, it is okay to make changes to them.

I would be okay with a new option to specify a custom template directory, I guess. It seems overkill to me, but I would accept such a feature, specially if there is also a way to copy one of the stock templates. Maybe something like:

    $ flask db template /path/to/templates/my-flask-template
    $ flask db template --multidb /path/to/templates/my-flask-multidb-template
    $ flask db init --template /path/to/templates/my-flask-template

But once again, it seems overkill. Much easier to create the repository then make the changes to your files manually!

**Comment by jslay88** [comment]
As I've stated before, it gives the developer control. 

I don't want to distribute an application, and then have to have them go and manually build out a config, and subsequently run a bunch of additional CLI commands that I can programmatically handle. 

There are tons of applications that have a "first run" interface. 

The current condition flask_migrate sits in, poses a lot of limitations and barriers to the developer, which can be solved with a few code changes, and even potentially help them make things a bit easier. The reason it seems like such a small use case, is because most developers that end up doing something like this, they likely would abandon trying to use flask_migrate due to the barriers previously mentioned. 

This is all about giving the developer more options, with little to no impact on this project as a whole. All 4 options I suggest would have little/no impact on existing users, but can increase the flexibility of the porject as a whole b

The fact that alembic hi-jacks your loggers, and you can make a slight code change to help in this situation, makes sense to me. Because now to get around that, I have to go through a whole series of not great solutions to eliminate those barriers.

**Comment by miguelgrinberg** [comment]
> I don't want to distribute an application, and then have to have them go and manually build out a config, and subsequently run a bunch of additional CLI commands that I can programmatically handle. 

If you distribute an application you will ship a migration repository with it, you will not ask your users to build one. What am I missing here?

**Comment by jslay88** [comment]
Nevermind. I give up. Apparently everything I have already said has no weight. Let's just keep things difficult and impossible to manage a life cycle from within the application. Makes more sense. Not like any other application does this or is common practice.

**Comment by aabounegm** [comment]
I was just facing this issue and spent more than 3 hours straight trying to fix it. At the end, I found that the root cause is the `fileConfig` line in env.py mentioned by @jslay88 in Option 1. However, the very simple solution that I finally reached is to change this line to `fileConfig(config.config_file_name, disable_existing_loggers=False)`. The last argument is True by default for historical reasons, and now my loggers remain. Also, I moved my `logging.config.dictConfig` call below the `upgrade` call to override with my own config.
