### ISSUE TITLE
Flask Migration , No table has been created while running flask db migrate -m "users table"?

### ISSUE THREAD

**Issue by ShashwatMishra** [miguelgrinberg/Flask-Migrate#264]

**Comment by ShashwatMishra** [comment]
Hi Miguel,
I am new in Flask development .
I followed this article.I am providing the link:-
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database
app.db file has been h=generated but in Terminal while running the command ;- 
flask db migrate -m "users table" 
it is giving "No changes in Schema  detected "

**Comment by miguelgrinberg** [comment]
This happens because you have a database already created. The migration framework works by looking at the differences between your model definitions and your database. If you created your database manually, then there are no differences and the migration framework has nothing else to do. If you can delete your database, then generating a migration should work as shown in the tutorial.
