### ISSUE TITLE
render_item method in env.py is not being called

### ISSUE THREAD

**Issue by cyberlake** [miguelgrinberg/Flask-Migrate#300]
There's an issue with the `sqlalchemy_utils` package. Special field types like UUID, Password from this library are not being recognized by alembic. There was a workaround in earlier versions of `flask-migrate` and that is to write custom `render_item` method in `env.py`:

```python
def render_item(type_, obj, autogen_context):
    """Apply custom rendering for selected items."""

    if type_ == 'type' and isinstance(obj, sqlalchemy_utils.types.uuid.UUIDType):
        # add import for this type
        autogen_context.imports.add("import sqlalchemy_utils")
        autogen_context.imports.add("import uuid")
        return "sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4"

    # default rendering for other objects
    return False
```

This was resulting in versions being correct, e.g. sqlalchemy_utils imported and `Column type` is correct. 

I upgraded to the latest `flask-migrate` from `2.3.1` and this workaround no longer works. Seems like the `render_item` method is not called at all.

**Comment by miguelgrinberg** [comment]
Flask-Migrate is not Alembic, it just wraps it. If render_item stopped working, it is something that will need to be fixed on the Alembic side, not here.

That said, I suggest you review your workflow, because it would be odd if this is something that broke within alembic. I suggest you review your own process with regards to setting up a render_item callback.
