### ISSUE TITLE
Fix for  Error: Can't locate revision identified by '3f915c78527a' built in

### ISSUE THREAD

**Issue by Anekdotin** [miguelgrinberg/Flask-Migrate#337]
Seems like this is a common feature.  Besides deleting all your data, perhaps integrate a script to fix this issue

**Comment by miguelgrinberg** [comment]
I disagree that this is a common problem. If this happens often for you, I think you should try to identify what is it that you are doing that is causing the problem, because this isn't supposed to happen unless you make manual changes to the migration scripts bypassing Flask-Migrate.

In any case, there is no generic way to fix this error. You need to know what the state of the database is to decide how to make a correction.

Also, note that this project does not perform any migration work. Flask-Migrate is a Flask friendly wrapper for Alembic. Even if there was a simple fix for this problem, it would be something that Alembic would do and Flask-Migrate will just pass it through to the developer.
