### ISSUE TITLE
change the migration settings

### ISSUE THREAD

**Issue by ddff12** [miguelgrinberg/Flask-Migrate#350]
Hi. Is there a way to change the migration multidb settings on the way?

"flask db init" 
　　↓
"flask db init --multidb"

Or can it be reset?

**Comment by miguelgrinberg** [comment]
There is no automatic conversion.

If you can start from scratch with a new migration repository, that's the easiest.

If you want to convert your existing single-db migrations to a multidb repository, I suggest you create a small multidb example project and generate a migration for it so that you see what the differences are. Then you can copy the env.py from this throwaway project to your real project, and adapt all your existing migrations to the required format for multi-database.

**Comment by richardkhillah** [comment]
I had the same question this morning. The script.py.mako file (in addition to env.py) had to be changed. The process of picking apart the migration scripts was tedious but, done carefully the throwaway project route works.

**Comment by ddff12** [comment]
Hi.
confirmed. I found a difference between the two files.
　env.py
　script.py.mako
Replacing these files seems to work.But we are considering recreating it.
Thank you very much!

**Comment by miguelgrinberg** [comment]
Thanks for sharing the results. I forgot about the `script.py.mako` file, which as you both stated, should also be copied over from the throwaway project.
