### ISSUE TITLE
How to test migrations?

### ISSUE THREAD

**Issue by voidus** [miguelgrinberg/Flask-Migrate#354]
I am trying to get testing going for my migrations, and had a look at pytest-alembic, but I had difficulties getting it going.

- If there is a known way on how to test it, it should be documented.
- If it is and I didn't find it I'm sorry. In that case, I propose to add it to the table of contents on the left side of https://flask-migrate.readthedocs.io/en/latest/
- If there is no known way, we should find one :)

**Comment by miguelgrinberg** [comment]
Good question! Thanks for alerting me of the pytest-alembic, didn't know that project.

I sort of always implement migration tests manually, but I spent a few minutes trying to get the pytest-alembic migrations to work. I had to add the following conftest.py to my project to adapt the defaults in pytest-alembic to Flask-Migrate:

```python
import pytest


@pytest.fixture
def alembic_config():
    """Override this fixture to configure the exact alembic context setup required.
    """
    return {'file': 'migrations/alembic.ini'}


@pytest.fixture
def alembic_runner(alembic_config, alembic_engine):
    """Produce an alembic migration context in which to execute alembic tests.
    """
    import pytest_alembic

    from app import create_app   # <--- this line and the next are dependent on your app structure
    app = create_app()

    with app.app_context():
        with pytest_alembic.runner(config=alembic_config,
                                   engine=alembic_engine) as runner:
            yield runner
```

This makes two changes. First, it tells pytest-alembic that the alembic.ini file is inside the migrations directory (Alembic likes to put it in the root folder of the project). The second change is to push a Flask application context when creating a migration context. This is required because Flask-Migrate uses the `db` object from Flask-SQLAlchemy to pass schema information to Alembic.

With these changes I was able to get 3 of the 4 tests from pytest-alembic passing. The test that does up/down every migration fails because I have the tests on this app I'm using configured to use sqlite, so the first DROP COLUMN it blows up. It should work fine on MySQL/Postgres, or if you enable batch mode.

Hope this helps!

**Comment by elizagraham** [comment]
@miguelgrinberg Nice work! This has been troublesome for me with writing test cases (i'm using Flask-SQLAlchemy & Flask-Migrate for db migrations). How should the `alembic_engine` be assigned a value in your code example above?

**Comment by miguelgrinberg** [comment]
@elizagraham the alembic_engine fixture is not used in any of the four tests that I come predefined with this plugin, so I did not need to do anything with it. Normally when you work with a Flask application you will not get a separate database engine, you will use the Flask-SQLAlchemy one.

**Comment by elizagraham** [comment]
@miguelgrinberg thanks for the explanation. Within your set up how have you configured the `env.py` file that gets generated in your migrations folder?

**Comment by miguelgrinberg** [comment]
@elizagraham I did not need to change anything in the migrations directory, I just added the conftest.py file shown above.

**Comment by elizagraham** [comment]
@miguelgrinberg yes that's what i'm trying to set up. I'm relatively new to python and flask and my trying to understand how to best setup the testing configuration for my Flask app. Currently within my `app` i can run `flask db migrate`  and `flask db upgrade` to run migrations on the main database and that works.

**Comment by miguelgrinberg** [comment]
There are a few ways to do this. For this exercise I used my Mega-Tutorial app, which overrides the `Config` class during testing: https://github.com/miguelgrinberg/microblog/blob/master/tests.py#L17.

**Comment by elizagraham** [comment]
@miguelgrinberg okay i will check that out thanks :)

**Comment by rdctmeconomou** [comment]
Thanks to this issue, I learned about pytest-alembic.  However, I could not get the above example working.  Here's what I did instead.

I have a parameterized `db_uri` fixture that uses the `tmp_path` pytest fixture and the pytest-postgresql plugin to create an empty database, returning the corresponding SQLAlchemy database URL.

```python
from pathlib import Path

import pytest
from psycopg import Connection
from sqlalchemy.engine import Engine, create_engine
from sqlalchemy.pool import NullPool

from ..models import Base


@pytest.fixture(
    params=[
        pytest.param("sqlite", marks=pytest.mark.smoke),
        pytest.param("postgresql", marks=pytest.mark.slow),
    ],
)
def db_uri(request: pytest.FixtureRequest) -> str:
    """Create an empty database.

    This returns a SQLAlchemy database URL;
    cf. <inv:sqlalchemy:std:doc#core/engines>.

    """
    match request.param:
        case "postgresql":
            fixture: Connection = request.getfixturevalue("postgresql")
            return (
                f"postgresql+psycopg://{fixture.info.user}"
                f":@{fixture.info.host}"
                f":{fixture.info.port}"
                f"/{fixture.info.dbname}"
                "?options=-c timezone=utc"
            )
        case "sqlite":
            fixture: Path = request.getfixturevalue("tmp_path")
            return f"sqlite:///{fixture / 'db.sqlite'}"


@pytest.fixture
def db_engine(db_uri: str) -> Engine:
    """Connect to the given test database via SQLAlchemy."""
    return create_engine(db_uri, poolclass=NullPool)


@pytest.fixture
def _db_init(db_engine: Engine):
    """Initialize the test database upon request."""
    Base.metadata.create_all(db_engine)
```

Separately, I have a fixture, `app_pre_init`, that creates a test instance of the Flask app without initializing the underlying database.

```python
import pytest
from flask import Flask

from ..app import create_app


@pytest.fixture
def app_pre_init(db_uri: str,...) -> Flask:
    """Yield a test instance of the Flask application.

    `db_uri`
    : Connection string for an empty test database;
      cf. <inv:sqlalchemy:std:doc#core/engines>.

    [...]

    """
    app = create_app(
        {
            "SQLALCHEMY_DATABASE_URI": db_uri,
            "TESTING": True,...
        }
    )...

    yield app

    # Tear down resources and clean up.
    pass


@pytest.fixture
def app(app_pre_init: Flask, _db_init: None) -> Flask:
    """Yield a test instance of the Flask application.

    Its test database has been initialized but is otherwise empty.

    `app_pre_init`
    : A Flask application with an empty test database.

    `_db_init`
    : Initializes the test database when referenced.

    """
    return app_pre_init
```

With this in place, I define pytest-alembic's `alembic_config` and `alembic_runner` fixtures using the Flask-Migrate configuration.  The only thing I haven't figured out is how best to handle multiple binds, but since I'm not using them yet, the`alembic_engine` is an alias for my existing `db_engine` fixture.

```python
from flask import Flask
from pytest_alembic.config import Config
from pytest_alembic.runner import MigrationContext, runner

from ..migrate import migrate


@pytest.fixture
def alembic_config(app_pre_init: Flask) -> Config:
    """Test migrations using the bundled Alembic configuration.

    `app_pre_init`
    : A test instance of the Flask application that starts with an
      empty test database.

    """
    with app_pre_init.app_context():
        yield Config(alembic_config=migrate.get_config())


@pytest.fixture
def alembic_engine(db_engine: Engine) -> Engine:
    """Connect pytest-alembic to configured test databases.

    `db_engine`
    : An open connection to an empty test database.

    """
    return db_engine


@pytest.fixture
def alembic_runner(
    alembic_config: Config, alembic_engine: Engine
) -> MigrationContext:
    """Yield an Alembic migration context for testing migrations.

    `alembic_config`
    : A handle on the bundled Alembic configuration.

    `alembic_engine`
    : An open connection to the empty test database.

    """
    with runner(config=alembic_config, engine=alembic_engine) as alembic_runner:
        yield alembic_runner
```

I did not change `run_migrations_online` as suggested in the pytest-alembic documentation.  The suggested changes are redundant given how Flask-Migrate's env.py injects the Flask-SQLAlchemy configuration into the Alembic configuration.

Finally, I added my own tests, which called the pytest-alembic tests.  This, plus pytest-order, allowed me to exercise the database migrations after unit/functional and integration testing but before end-to-end testing.

```python
import pytest
from pytest_alembic import tests
from pytest_alembic.runner import MigrationContext


@pytest.mark.order("second_to_last")
def test_single_head_revision(alembic_runner: MigrationContext):
    """Assert that there only exists one head revision.

    `alembic_runner`
    : An Alembic migration test execution context.

    """
    tests.test_single_head_revision(alembic_runner)


@pytest.mark.order("second_to_last")
def test_upgrade(alembic_runner: MigrationContext):
    """Try upgrading through each revision.

    `alembic_runner`
    : An Alembic migration test execution context.

    """
    tests.test_upgrade(alembic_runner)


@pytest.mark.order("second_to_last")
def test_model_definitions_match_ddl(alembic_runner: MigrationContext):
    """Make sure the migrations and the current data model match.

    `alembic_runner`
    : An Alembic migration test execution context.

    """
    tests.test_model_definitions_match_ddl(alembic_runner)


@pytest.mark.order("second_to_last")
def test_up_down_consistency(alembic_runner: MigrationContext):
    """Check all downgrades.

    `alembic_runner`
    : An Alembic migration test execution context.

    """
    tests.test_up_down_consistency(alembic_runner)
```
