### ISSUE TITLE
Updating column type to ARRAY does not register as a change

### ISSUE THREAD

**Issue by thinkingfield** [miguelgrinberg/Flask-Migrate#365]
I had a db column that was initially of type String using SQLAlchemy. When I changed the column type to ARRAY('String') in my app (class declaration), migrate did not see this as a change. It did not generate an upgrade script, it just ignored the change. I had to go in and manually delete the table and then do a migration.

**Comment by miguelgrinberg** [comment]
This is the repository for Flask-Migrate, which is a wrapper for Alembic. Your issue is with Alembic, but note that this package does not check column types by default, that needs to be enabled. See https://stackoverflow.com/questions/33944436/flask-migrate-and-changing-column-type/52181159#52181159 for the solution that I think will apply to your case.

**Comment by thinkingfield** [comment]
> This is the repository for Flask-Migrate, which is a wrapper for Alembic. Your issue is with Alembic, but note that this package does not check column types by default, that needs to be enabled. See https://stackoverflow.com/questions/33944436/flask-migrate-and-changing-column-type/52181159#52181159 for the solution that I think will apply to your case.

Thank you for the quick response.
