### ISSUE TITLE
Using sqlalchemy models inside migration to create or modify data

### ISSUE THREAD

**Issue by kettenbach-it** [miguelgrinberg/Flask-Migrate#369]
Hello,

I know that Flask-Migrate/Alembic is primarily intended to manage the database schemas and not to edit data - but unfortunately I frequently have the job of changing data via migrations.

Since I have built beautiful models for my database with Flask-sqlalchemy, I find it extremely cumbersome to use any bulk-load operations of alembic or raw-sql-statements with "execute" from sqlalchemy to change data.
Instead I would like to use my models like I do in the rest of the application. For example like to do this:

```
from db import SESSION
from init import APP
from models.user import User

def upgrade():
    with APP.app_context():
        old_user = SESSION.query(User).filter(User.id == 12345).one()
        old_user.name = "The new name of the user"
        SESSION. add(old_user)
        SESSION.commit()
```

I played around a lot and read about the mysterious app context.
In the end I always end up running into the error:

```
INFO  [alembic.runtime.migration] Running upgrade 332a40dcab1f -> 7c3f5a8262ac
ERROR [root] Error: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

I thought this is done by "with APP.app_context()" but it seems not.

Question is: how do I do this correctly?

**Comment by miguelgrinberg** [comment]
Nothing in the code that you posted could cause the error that you are getting. It would be useful to see the stack trace of the error, so that I can have more context into what is causing it.

> Question is: how do I do this correctly?

I'm not sure what the error is, but I'm going to answer this question anyway, because you will continue having problems eve after you solve the current one.

Using your application models in migrations is going to bring you a lot of pain and suffering, and can make your migrations fail unexpectedly as your models are updated or changed, so don't do it. The only safe way to use ORM models in migration scripts is to duplicate the model definitions that you need in each migration script, so that the script remain self-contained.

**Comment by kettenbach-it** [comment]
Thanks a lot! I will continue to work with the existing "execute()" solution!
