### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table sqlite_sequence may not be dropped

### ISSUE THREAD

**Issue by Mr-NB** [miguelgrinberg/Flask-Migrate#375]
when i run 'db migrate' , show 
![image](https://user-images.githubusercontent.com/35053330/100549708-9414f880-32af-11eb-8911-ccb64835b4ff.png)
 
Then i run  'db upgrade' ,i get expection:

![image](https://user-images.githubusercontent.com/35053330/100549726-b444b780-32af-11eb-8624-eb444203cc49.png)

how can i ignore sqlite_sequence ???

Libary version:
flask-migrate 2.5.3
flask-sqlalchemy 2.4.4
python 2.7.16

**Comment by miguelgrinberg** [comment]
Alembic should ignore this table, since it is internal to SQLite. I do not know what in your application this is not ignored, it could be a bug with Alembic. I suggest you try regenerating your database to see if the problem continues. In that case you will need to submit a bug to the Alembic project.

**Comment by svanscho** [comment]
@Mr-NB did you fix this in the end? Is there any documentation you could point me to?

**Comment by elandorr** [comment]
@svanscho Here's my interim fix: https://github.com/sqlalchemy/alembic/issues/1062
