### ISSUE TITLE
No changes in schema detected.

### ISSUE THREAD

**Issue by tabebqena** [miguelgrinberg/Flask-Migrate#378]
I know this is repeated issue, but no fix worked for me.
.
Desription: 
- I created new table named `Lesson`
- I imported it, before running `migrate.init_app(app, db, compare_type=True)` 
- In migrations/env.py file, I imported the `Lesson` model before the line `from flask import current_app`
- Then I ran `flask db migrate -m 'lessons table'`

Expectation:
- Create migration file.

Error occured:
- No migration file created.
- The lesson table was created in the db.

**Comment by miguelgrinberg** [comment]
You seem to have some confusion regarding how things work with Flask-Migrate and Alembic.

> I imported it, before running migrate.init_app(app, db, compare_type=True)

You should import all your models somewhere in your app, but this has nothing to do with Flask-Migrate, you are doing it so that SQLAlchemy knows about the model. The location of the import is completely irrelevant.

> In migrations/env.py file, I imported the Lesson

What is the purpose of this? The env.py file rarely needs to be modified.

> No migration file created.

Probably because the lesson table exists in your database.

> The lesson table was created in the db.

Right. So who created it? The `flask db migrate` command does not create any tables. If you created this table using something like `db.create_all()` that is the problem, you are using two different methods to update your database. Remove the table, and remove the call to `create_all()` the repeat the migration steps to generate a new migration.

**Comment by tabebqena** [comment]
Thanks for reply @miguelgrinberg .

- The problem solved by removing the line which call 'createAll()'.
- To report this conflict, the line was called to create `sessions` table for the `flask-Session` plugin.

- many answers as: [answer](https://stackoverflow.com/a/59184349/2390992), [answer2](https://stackoverflow.com/a/62924439/2390992) suggest to edit `migrations/env.py`
- As I understood from your replay [here](https://github.com/miguelgrinberg/Flask-Migrate/issues/317#issuecomment-593419084) & [here](https://github.com/miguelgrinberg/Flask-Migrate/issues/317#issuecomment-593419084); It is necessary to import models before calling `SQLAlchemy`  & `Migrate`. 

Thank you very much

**Comment by miguelgrinberg** [comment]
> many answers as: answer, answer2 suggest to edit migrations/env.py

These two answers are not authoritative. It's just random people who did this. The env.py is in general complete as it is generated. Import your models in your own application, not in env.py.

In some cases you do need to make changes to env.py, but this isn't one of them.

> As I understood from your replay here & here; It is necessary to import models before calling SQLAlchemy & Migrate.

The models need to be imported because they are automatically registered with SQLAlchemy when they are imported. If you don't imported then SQLAlchemy does not know about them. Flask-Migrate and Alembic have nothing to do with this though, they are affected by this because they get the list of models from SQLAlchemy.

**Comment by tabebqena** [comment]
Thank you @miguelgrinberg , very good illustration.

**Comment by tabebqena** [comment]
Thank you @miguelgrinberg , Very adequate clarification.
