### ISSUE TITLE
SQLALCHEMY_DATABASE_URI missing from config doesnt cause any warning/error

### ISSUE THREAD

**Issue by asmodehn** [miguelgrinberg/Flask-Migrate#58]
It might be a useless thing to check for, but I already spent a few hours trying to figure out why my database was not created.

I had issues with multiple configurations and somehow the SQLALCHEMY_DATABASE_URI value was not set before initializing SQLAlchemy.
Not sure what the Flask-Migrate behaviour should be in that case...

For me everything was working fine : 
`db init` created the migration folder
`db migration`created the migration from my models.py
`db upgrade` applied the migration.

Things were more problematic when I realized that `db upgrade` kept applying the migration, and that my app.db was nowhere to be found.

**Comment by miguelgrinberg** [comment]
This is unfortunate, yes. I think your problem is that Flask-SQLAlchemy has a default for SQLALCHEMY_DATABASE_URI. If you don't set it, then Flask-SQLAlchemy defines it as `sqlite://`, which sets up an in-memory SQLite database. So you couldn't find a database file because the database was held in memory.

**Comment by asmodehn** [comment]
Makes sense... and after having a look there : https://www.sqlite.org/inmemorydb.html I realized that "The database ceases to exist as soon as the database connection is closed." that explains it all.
Thanks !
