### ISSUE TITLE
Do not generate empty migrations

### ISSUE THREAD

**Issue by italomaia** [miguelgrinberg/Flask-Migrate#65]
I noticed that whenever "db migrate" command is run, it creates a new migration, even empty ones. This does not seem to be a useful behavior. It would be nice if, instead of a empty migration being generated, just a message "Project model has no changes do migrate" was printed.

**Comment by miguelgrinberg** [comment]
You may want to suggest this to the Alembic project, since that is where the migrations happen.

**Comment by zzzeek** [comment]
here's how you can do this now (should be a cookbook entry):  https://bitbucket.org/zzzeek/alembic/issues/80/autogenerate-should-have-an-option-to-skip#comment-20502176

**Comment by miguelgrinberg** [comment]
Awesome. Thanks @zzzeek! I'll update my env.py with this change.

**Comment by zzzeek** [comment]
here's that: http://alembic.readthedocs.org/en/latest/cookbook.html#don-t-generate-empty-migrations-with-autogenerate  you need alembic 0.8 for it to work

**Comment by miguelgrinberg** [comment]
This is now available in release 1.5.1. Since this functionality is implemented in the `env.py` file, existing migration repositories will only start detecting empty migrations once the `env.py` is manually updated.

@zzzeek Thanks for your help with this. The single db version of my `env.py` was easy to adapt, but it was tricky to make this work for the multidb version. May be useful to add a note in the cookbook about the fact that the callback is called for every db, but only in the last call the migration script is complete and can be inspected to see if it is empty or not.

**Comment by zzzeek** [comment]
@miguelgrinberg multidb integration with this hook just landed in 0.8.1 yesterday.   for details on how that should be dealt with see the notes at http://alembic.readthedocs.org/en/latest/api/autogenerate.html#revision-generation-with-multiple-engines-run-migrations-calls

**Comment by miguelgrinberg** [comment]
@zzzeek Thanks. Yes, I have basically done it as you suggest in those notes.

**Comment by zzzeek** [comment]
ok great.  I totally missed mutlidb in 0.8.0 and had an all day freakout getting that fix in place.   I considered moving the hook outside of per-DB, but i want it to work w/ DB access as well, so I figured the "use only the last run of the hook" approach was the least evil.
