### ISSUE TITLE
Allow initialialization with just db and app later

### ISSUE THREAD

**Issue by johtso** [miguelgrinberg/Flask-Migrate#89]
Currently the `Migrate` extension class allows you to instantiate it with just a `db` and no `app`, but in that case it just throws it away as if it was never provided. https://github.com/miguelgrinberg/Flask-Migrate/blob/master/flask_migrate/__init__.py#L29

Do you think it would make sense to allow supplying the `db` at instantiation time and the `app` at `init_app` time?

**Comment by italomaia** [comment]
I also need lazy initialization of app.

**Comment by miguelgrinberg** [comment]
@italomaia you can do lazy app initialization as you do with any other Flask extension. Just use `init_app` and pass `app` and `db` instances then.

**Comment by italomaia** [comment]
@miguelgrinberg yes, I can, but there is a problem (for me) to that approach. If I want to treat flask-migrate as any other flask extension, make a code pattern and load it "auto-magically" together with other extensions, I "kind of" can't because most extensions allow lazy initialization with just app. I would have to create a exception just for flask-migrate. Depending on the approach, it would also be necessary to change how the (my) project is sorted and so on. 

Let's take flask-empty as an example: right now, all extensions are instantiated in an extensions module/or package. I cannot use that approach with flask-migrate as of now. 

Are **there** cons to initialize the extension, optionally, with just app?

**Comment by miguelgrinberg** [comment]
Not sure I understand. The `db` argument is a required argument, it is not optional. Flask-Migrate does not work if it is not given the `db` instance. So if you are asking if Flask-Migrate can somehow figure out where the db is on its own, then the answer is no. Also note that Flask does not require that `init_app` takes a single `app` argument. Extensions are free to implement `init_app` with any necessary arguments.

Not that it matters, but here is another Flask extension (not mine) that uses extra arguments: https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L403-L408

**Comment by italomaia** [comment]
Flask does not require that init_app takes a single app, true, and I'm not saying that is bad thing. My problem (maybe someone else's too) is that the following does not work:

```
db = SQLAlchemy()
# hey migrate, this is my db instance
migrate = Migrate(db)
app = Flask('name')

# migrate could already be aware of db by this point
# why provide it again?
migrate.init_app(app)
```

Imagine I have a **db** instance and a **migrate** instance defined in the same module. In that case, db could be provided to migrate. Consider that the Flask instance might not be available at that point. 
Then, imagine I want to lazy initialize them and I only have access to one extension instance at any given time (during initialization), being required to initialize migrate with **app** AND **db**, given migrate already received db, would cause quite the trouble. 

Case you're wondering, extensions cannot see each other during setup to simplify configuration.

**Comment by miguelgrinberg** [comment]
Take a look at version 1.8.0, recently release. This version does what you want, i.e. you can pass `db` when you instantiate the extension, and `app` when you call `init_app()`.
